[project]
name = "app3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pkg-settings",
    "uvicorn>=0.34.0",
]

[tool.uv.sources]
pkg-settings = { workspace = true }
