[project]
name = "pkg-requests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pkg-settings",
]

[tool.hatch.build.targets.wheel]
packages = ["src/pkg_requests"]

[tool.uv.sources]
pkg-settings = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
