[project]
name = "pkg-database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["asyncpg>=0.30.0", "pkg-settings"]

[tool.uv.sources]
pkg-settings = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/pkg_database"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
